### PR TITLE
Fixes for iOS-Bugs, Code Modernization & lowercase enum-members in dart

### PR DESCRIPTION
**Pull request by imdatceleste**
### 1. Bug-fix iOS
There was mismatch of `value` and `path` in the Swift Sharing-code. This resulted in a crash. I fixed this.
 
Since I have only iOS 16 to test with, I am now supporting both keys in incoming data from iOS, i.e. `path` **and** `value` when converting the data to JSON.

Then, if there is anything in `path`, I still use it.

### 2. Modernize Swift-Code
Also modernized the Swift-Code. 
- Move to `guard`
- Early Return whenever possible
- Implement all editor suggestions

### 3. dart
- Convert to camel-Case (lowercase) enum members

## Comment
There is one warning left in Swift-code due to new SDK. This can be fixed by implementing the corresponding function as `async` as that only works with Swift 5.5

### CODE REVIEW

**Comment by michaelmartins09** [comment]
Thank you @imdatsolak !! Your changes worked for me \o/

**Comment by imdatsolak** [comment]
> Hi, any updates on this PR acception? How can i test your latest suggestions, @imdatsolak ?

You can just use my repo. Put this in your `pubspec.yaml`:

``` yaml
flutter_sharing_intent:
   git:
      url: git@github.com:imdatsolak/flutter_sharing_intent.git
      ref: imdatsolak/ios-fix
```

**Comment by simonegiammy** [comment]
Hi, I'm trying to try your fix but I'm getting this error: 
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
any help?

**Comment by imdatsolak** [comment]
> Hi, I'm trying to try your fix but I'm getting this error:
> [git@github.com](mailto:git@github.com): Permission denied (publickey).
> fatal: Could not read from remote repository.
> any help?

If you are talking to me: you need to have access to github using your SSH key, otherwise access via SSH won't work.

If you can't use an SSH key, you might need to go to my repo and get the HTTPs-clone URL and replace `git:github.com...` with that URL.

**Comment by kristofb** [comment]
Hello @imdatsolak, may you synchronize your branch with bhagat-techind/flutter_sharing_intent and update the PR ? I hope this will help for the PR. And also, you should remove from your PR the team ID changes from XCode project, and keep that only locally on your computer; this will reduce the changes. 
I'll work on a merge of both branch for the moment.
Thanks

**Comment by imdatsolak** [comment]
@kristofb made the necessary changes (I hope). Please check.

Also, the Team ID is done automatically by Xcode and required for testing purposes. Since this is a share-extension, it is actually a lot of changes to revert before sending a PR.

I see the problem, I have atm, no idea how to make that easier for the maintainer and contributors.

I did make the changes manually with a text-editor. You probably still need to check them.

**Comment by Firooz-Smart** [comment]
Thank you sir @imdatsolak  you saved my time after 4 days i found this helpful. worked for me.

**Comment by zhusupq** [comment]
@bhagat-techind Hi man! why this pr not merged?)

**Comment by juanan-onelife** [comment]
Thank you @imdatsolak for the solution!

**Comment by alodevloper** [comment]
Hello @imdatsolak  , it gives me this error , any help ?

Swift Compiler Error (Xcode): Cannot find type 'SharingFile' in scope
/..Share%20Extension/ShareViewController.swift:14:26
ShareViewController.swift:14

Swift Compiler Error (Xcode): Cannot find type 'SharingFileType' in scope
/..e/ios/Share%20Extension/ShareViewController.swift:248:47

**Comment by alodevloper** [comment]
> Thank you sir @imdatsolak you saved my time after 4 days i found this helpful. worked for me. now i can receive text/url and images in my app

hello @Firooz-Smart could you tell me what steps you follow?

**Comment by imdatsolak** [comment]
> Hello @imdatsolak , it gives me this error , any help ?
> 
> Swift Compiler Error (Xcode): Cannot find type 'SharingFile' in scope /..Share%20Extension/ShareViewController.swift:14:26 ShareViewController.swift:14
> 
> Swift Compiler Error (Xcode): Cannot find type 'SharingFileType' in scope /..e/ios/Share%20Extension/ShareViewController.swift:248:47

I can't really reproduce what you are doing. If you get my fork as described [here](https://github.com/bhagat-techind/flutter_sharing_intent/pull/21#issuecomment-1663918456) you shouldn't have any problems.

I don't know what @bhagat-techind is currently doing with merging since it created merge conflicts compared to their changes, but I am actively using my fork in my projects and I don't see any problems there.

**Comment by alodevloper** [comment]
> > Hello @imdatsolak , it gives me this error , any help ?
> > Swift Compiler Error (Xcode): Cannot find type 'SharingFile' in scope /..Share%20Extension/ShareViewController.swift:14:26 ShareViewController.swift:14
> > Swift Compiler Error (Xcode): Cannot find type 'SharingFileType' in scope /..e/ios/Share%20Extension/ShareViewController.swift:248:47
> 
> I can't really reproduce what you are doing. If you get my fork as described [here](https://github.com/bhagat-techind/flutter_sharing_intent/pull/21#issuecomment-1663918456) you shouldn't have any problems.
> 
> I don't know what @bhagat-techind is currently doing with merging since it created merge conflicts compared to their changes, but I am actively using my fork in my projects and I don't see any problems there.

thank you it works now , thanks for the effort

**Pull request closed without merging**
